### ISSUE TITLE
[future request](Python package)

### ISSUE THREAD

**Issue by ttlns** [Smartproxy/Selenium-proxy-authentication#3]
Make it a python package (reference: https://github.com/tomchen/example_pypi_package) and [upload to pypi](https://packaging.python.org/en/latest/tutorials/packaging-projects/#uploading-the-distribution-archives) so it is installable using `pip install package_name`

**Comment by ttlns** [comment]
@ZilvinasSP any information on why this got closed?

**Comment by sakanamk** [comment]
@kaliiiiiiiiii Hey, I've closed this issue because it's been a while, and I wasn't sure if it was still relevant. We do not plan to make a Python package for this code, as it's simply an example of how our proxies can be integrated with Selenium. If it's still relevant, let me know and I'll see what I can do.
